#ifndef WFMCODE_H_HEADER_INCLUDED
#define WFMCODE_H_HEADER_INCLUDED

// 流程及活动状态值定义
#define STAT_RUNNING		0
#define STAT_NOT_START		1
#define STAT_SUSPEND		2
#define STAT_ABORT			3
#define STAT_TERMINATE		4
#define STAT_COMPLETE		5

// WFM API返回值定义
#define WM_SUCCESS						0
#define WM_RUNNING						1
#define WM_TERMINATE					2
#define WM_INVALID_SESSION_HANDLE		3
#define WM_INVALID_PROCESS_DEFINITION	4
#define WM_INVALID_PROCESS_INSTANCE		5
#define WM_INVALID_ACTIVITY_INSTANCE	6
#define WM_INVALID_STATE				7
#define WM_INVALID_PARAMETER			8
#define WM_INVALID_FILTER				9
#define WM_INVALID_WORKITEM				10
#define WM_INVALID_SOURCE_USER			11
#define WM_INVALID_TARGET_USER			12
#define WM_CONNECT_FAILED				13
#define WM_APPLICATION_NOT_STARTED		14
#define WM_APPLICATION_NOT_DEFINED		15
#define WM_APPLICATION_BUSY				16
#define WM_INVOKE_APP_FAILED			17
#define WM_SYSTEM_ERROR					18
#define WM_MANUAL_PROC					19
#define WM_NOT_SUPPORT					99

#endif /* WFMCODE_H_HEADER_INCLUDED_B86446E9 */
